### ISSUE TITLE
EventsourcedActor_in_stateSync_mode_must_support_repeated_user_stash_unstash_operations_that_are_within_write() sometimes pass sometimes fail, fail mostly

### ISSUE THREAD

**Issue by imkow** [Horusiath/Eventuate.NET#2]
ATS.

Eventuate.Tests.EventsourcedActorSpec.EventsourcedActor_in_stateSync_mode_must_support_repeated_user_stash_unstash_operations_that_are_within_write

Akka.TestKit.Xunit2.Internals.AkkaEqualException : Assert.Equal() Failure
Expected: Pong(5)
Actual:   Pong(4)
   at Akka.TestKit.Xunit2.XunitAssertions.AssertEqual[T](T expected, T actual, String format, Object[] args)
   at Akka.TestKit.TestKitBase.<>c__DisplayClass93_0`1.<ExpectMsg>b__0(T m)
   at Akka.TestKit.TestKitBase.<>c__DisplayClass104_0`1.<InternalExpectMsgEnvelope>b__2(T m, IActorRef sender)
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog)
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint)
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint)
   at Akka.TestKit.TestKitBase.ExpectMsg[T](T message, Nullable`1 timeout, String hint)
   at Eventuate.Tests.EventsourcedActorSpec.EventsourcedActor_in_stateSync_mode_must_support_repeated_user_stash_unstash_operations_that_are_within_write() in D:\projects\Eventuate.NET\src\Eventuate.Tests\EventsourcedActorSpec.cs:line 502

[DEBUG][7/27/2019 4:03:16 PM][Thread 0014][[akka://test/user/$a#1431671600]] RECEIVED 'Cmd(payload: a, num: 1)' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'stash-on' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'Ping(1)' while stashing=True
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'stash-off' while stashing=True
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'Ping(2)' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'unstash' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'Ping(1)' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'Ping(3)' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'Ping(4)' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'Ping(5)' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0013][[akka://test/user/$a#1431671600]] RECEIVED 'Cmd(payload: b, num: 1)' while stashing=False
[DEBUG][7/27/2019 4:03:16 PM][Thread 0004][ActorSystem(test)] System shutdown initiated
[DEBUG][7/27/2019 4:03:16 PM][Thread 0011][EventStream] Shutting down: StandardOutLogger started
[DEBUG][7/27/2019 4:03:16 PM][Thread 0011][EventStream] All default loggers stopped

**Comment by imkow** [comment]
looks like a Akka.NET problem?

**Comment by Horusiath** [comment]
Yes, I know it's a flacky test - when using R# test runner it fails usually on Run All tests, while it passed when run individually. I'll address it later on.
